config/routes.rb
OpenPhysics::Application.routes.draw do
  resources :users
  resource :user_sessions
  resources :problems
  resources :pages
  match '/login', :to => 'user_sessions#new'
  match '/logout', :to => 'user_sessions#destroy'
  match '/welcome', :to => 'pages#welcome'

  root :to => 'pages#welcome'

end

app/models/problem.rb
class Problem < ActiveRecord::Base
  versioned
  has_many :solutions
  has_many :problem_tags
  has_many :tags, :through => :problem_tags

  before_save :parse_tags



  private

  def parse_tags
    tags = []
    /!#\/([\w\/]*)/.match(self.statement)[1].split("/").each do |t|
      tags += [Tag.find_or_create_by_name(:name => t)]
    end
    self.tags = tags
  end
  
end

app/models/problem_tag.rb
class ProblemTag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :problem
end

app/models/solution.rb
class Solution < ActiveRecord::Base
  belongs_to :problem
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :problem_tags
  has_many :problems, :through => :problem_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base 
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end

  def persisted?
    false
  end
end

app/controllers/application_controller.rb
require "authlogic"
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user_session, :current_user, :signed_in?

  def current_user_session
    @current_user_session ||= UserSession.find
  end

  def current_user
    @current_user ||= current_user_session && current_user_session.user
  end

  def authenticate
    unless current_user
      deny_access
      return false
    end
  end


  def signed_in?
    !current_user.nil?
  end

  def sign_in(user)
    activate_authlogic
    UserSession.create(user)
  end

  def deny_access
    store_location
    redirect_to login_path, :notice => "Please sign in to access this page"
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  private
  def store_location
    session[:return_to] = request.fullpath
  end

  def clear_return_to
    session[:return_to] = nil
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end

  def search
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  def new
    @problem = Problem.new
    @solution = Solution.new
  end

  def create
    @problem = Problem.new(params[:problem])
    if @problem.save
      flash[:success] = "New Problem Created!"
    else
      render 'new'
    end
    @solution = @problem.solutions.build(params[:solution])
    @solution.save!
    redirect_to problems_path
  end

  def edit
    @problem = Problem.find(params[:id])
    @solution = @problem.solutions.first
  end

  def update
    @problem = Problem.find(params[:id])

    @solution = @problem.solutions.first

    if @problem.update_attributes(params[:problem])
      flash[:success] = "Problem updated!"
    else
      render 'edit'
    end
    @solution.update_attributes(params[:solution])

    redirect_to problems_path
  end

  def show
    @problem = Problem.find(params[:id])
    @problem.revert_to(params[:version].to_i) if params[:version] 
  end

  def index
    @problems = Problem.all

    respond_to do |format|
      format.html
      format.xml { render :xml => @problems.to_xml(:include => [:solutions, :tags]) }
    end

  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  # GET /user_sessions/new
  # GET /user_sessions/new.xml
  def new
    @user_session = UserSession.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user_session }
    end
  end

  # POST /user_sessions
  # POST /user_sessions.xml
  def create
    @user_session = UserSession.new(params[:user_session])

    respond_to do |format|
      if @user_session.save
        format.html { redirect_to(:users, :notice => 'Login Successful') }
        format.xml  { render :xml => @user_session, :status => :created, :location => @user_session }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user_session.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /user_sessions/1
  # DELETE /user_sessions/1.xml
  def destroy
    @user_session = UserSession.find
    @user_session.destroy

    respond_to do |format|
      format.html { redirect_to(:users, :notice => 'Goodbye!') }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :show, :update, :destroy, :index]
 
  def index
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
    if (@user != @current_user)
      flash[:error] = "You don't have the right permissions!"
      redirect_to users_path 
      return
    end

  end

  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if (@user != @current_user)
      flash[:error] = "You don't have the right permissions!"
      redirect_to users_path 
      return
    end

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    if @current_user.perm != "admin"
      flash[:error] = "You don't have permissions to do that!"
      redirect_to users_path
      return
    end

    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def authenticate
    deny_access unless signed_in?
  end

  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page"
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  private
  def user_from_remember_token
    User.authenticate_with_salt(*remember_token)
  end

  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def clear_return_to
    session[:return_to] = nil
  end
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OpenPhysics</title>
  <%= stylesheet_link_tag :all %>
  <%= stylesheet_link_tag 'ui-lightness/jquery.ui' %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "jquery.js" %>
  <%= javascript_include_tag "jquery.ui.min" %>
  <%= csrf_meta_tag %>
  <%= javascript_include_tag "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" %>
</head>
<body>

  <div id="nav">
    <% if current_user %>
      <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
      <%= link_to "Logout", :logout %>
    <% else %>
      <%= link_to "Register", new_user_path%>
      <%= link_to "Login", :login %>
    <% end %>
  </div>


  <% if content_for?(:flash_msg) %>
    <%= yield(:flash_msg) %>
  <% else %>
    <%= render(:partial => 'shared/flash', :locals => { :flash => flash }) %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/pages/welcome.html.erb
<script>
  $(function() {
    var tags = [];
    $.get('/problems.xml', function(data) {
      var problems = $(data);
      problems.find('problem').each(function(){ 
        $(this).find('tag').each(function(){
          tags.push($(this).find('name').text());
        });
      });
      $( "#tags" ).autocomplete({
        source: $.unique(tags)
      });
      console.log(tags);
    });
  /*  var availableTags = [
    "ActionScript",
    "AppleScript",
    "Asp",
    "BASIC",
    "C",
    "C++",
    "Clojure",
    "COBOL",
    "ColdFusion",
    "Erlang",
    "Fortran",
    "Groovy",
    "Haskell",
    "Java",
    "JavaScript",
    "Lisp",
    "Perl",
    "PHP",
    "Python",
    "Ruby",
    "Scala",
    "Scheme"
    ];
    console.log(tags);
    $( "#tags" ).autocomplete({
     // source: availableTags
     source: availableTags
    });*/
  });
</script>

<h1>Open Source Physics!</h1>
<p>Because the world needs a databse of open-source physics problems.</p>

<div class="ui-widget">
  <label for="tags">Tags: </label>
  <input id="tags" />
</div>

app/views/problems/_form.html.erb
<%= form_for @problem  do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name%><br />
    <%= f.text_field :name%>
  </div>
  <div class="field">
    <%= f.label :statement %><br />
    <%= f.text_area :statement %>
  </div>
  <%= fields_for @solution do |s| %>
    <div class="field">
      <%= s.label :content, "Solution" %><br />
      <%= s.text_area :content %>
    </div>
  <% end%> 
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/problems/_problem.html.erb
<h2>Problem <%= problem.name %></h2><%= link_to "Show", problem_path(problem) %> | <%= link_to "Edit", edit_problem_path(problem)  %> | Version <%= problem.version %> <% if problem.version > 1 %>
|  <%= link_to "prev. version", problem_path(problem, :version => problem.version - 1) %> 
<% end%>
<p><%= problem.statement %></p>
<h2>Solution:</h2>
<p><%= problem.solutions.first.content %></p>

app/views/problems/edit.html.erb
<h1>Edit <%= @problem.name %> </h1>
<%= render 'form' %>

app/views/problems/index.html.erb
<h1>Problem List</h1>
<%= render @problems %>


<h1>Add a new problem</h1>
<%= link_to "New Problem", new_problem_path %>

app/views/problems/new.html.erb
<h1>Create a new problem</h1>

<%= render 'form' %>

app/views/problems/show.html.erb
<%= render @problem %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="error">
    <p>There were problems with the following fields:</p>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="flash <%= key %>"><%= value %></div>
<% end %>

app/views/user_sessions/_form.html.erb
<%= form_for(@user_session) do |f| %>
  <% if @user_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_session.errors.count, "error") %> prohibited this user_session from being saved:</h2>

      <ul>
      <% @user_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_sessions/edit.html.erb
<h1>Editing user_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_session %> |
<%= link_to 'Back', user_sessions_path %>

app/views/user_sessions/index.html.erb
<h1>Listing user_sessions</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_sessions.each do |user_session| %>
  <tr>
    <td><%= user_session.username %></td>
    <td><%= user_session.password %></td>
    <td><%= link_to 'Show', user_session %></td>
    <td><%= link_to 'Edit', edit_user_session_path(user_session) %></td>
    <td><%= link_to 'Destroy', user_session, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User sesson', new_user_session_path %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/user_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user_session.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user_session.password %>
</p>


<%= link_to 'Edit', edit_user_session_path(@user_session) %> |
<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<p id="notice"><%= notice %></p>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
  <% if current_user.perm == "admin" %> <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td><% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>